// FIX: Replaced deprecated 'GenerativePart' with 'Part' using an alias, as 'GenerativePart' is no longer exported from '@google/genai'.
import { GoogleGenAI, Modality, Part as GenerativePart } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });
const model = 'gemini-2.5-flash-image';

const callGemini = async (parts: GenerativePart[]): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: { parts },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                const mimeType = part.inlineData.mimeType;
                return `data:${mimeType};base64,${base64ImageBytes}`;
            }
        }
        
        throw new Error("No image was generated by the API.");

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to communicate with the AI model. Please check your API key and try again.");
    }
};

export const generatePaintingFromImage = async (
    imagePart: GenerativePart,
    prompt: string
): Promise<string> => {
    const textPart = { text: prompt };
    const parts: GenerativePart[] = [textPart, imagePart];
    
    return callGemini(parts);
};
